/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    organizations: Organization;
    'org-memberships': OrgMembership;
    categories: Category;
    tags: Tag;
    datasets: Dataset;
    resources: Resource;
    'audit-logs': AuditLog;
    teams: Team;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    'org-memberships': OrgMembershipsSelect<false> | OrgMembershipsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    datasets: DatasetsSelect<false> | DatasetsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  strictDraftTypes: true;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  systemRole: 'sysadmin' | 'user';
  isActive: boolean;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  logo?: (number | null) | Media;
  isActive?: boolean | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "org-memberships".
 */
export interface OrgMembership {
  id: number;
  user: number | User;
  organization: number | Organization;
  orgRole: 'owner' | 'admin' | 'member';
  joinedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  parent?: (number | null) | Category;
  level?: number | null;
  isActive?: boolean | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Calculado automáticamente. No editar manualmente.
   */
  usageCount?: number | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets".
 */
export interface Dataset {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  organization: number | Organization;
  category?: (number | null) | Category;
  tags?: (number | Tag)[] | null;
  license?: ('cc-by' | 'cc-by-sa' | 'cc-by-nc' | 'odc-by' | 'odbl' | 'public-domain' | 'other') | null;
  /**
   * Descripción de la licencia personalizada — requerido si licencia es "Otro".
   */
  licenseCustom?: string | null;
  status?: ('active' | 'archived' | 'disabled') | null;
  editorialStatus?: ('draft' | 'in_review' | 'approved' | 'rejected') | null;
  visibility?: ('private' | 'org_only' | 'public') | null;
  /**
   * Visibilidad solicitada por el steward. El owner aprueba o rechaza.
   */
  visibilityRequest?: ('org_only' | 'public') | null;
  /**
   * Fecha en que el steward hizo la solicitud de visibilidad.
   */
  visibilityRequestedAt?: string | null;
  collaborators?:
    | {
        user: number | User;
        role: 'steward' | 'editor' | 'viewer';
        assignmentType: 'direct' | 'team';
        /**
         * ID del team que originó esta asignación (Plus v1)
         */
        teamId?: string | null;
        /**
         * Snapshot del orgId del usuario al momento de asignar
         */
        orgIdAtAssignment?: number | null;
        assignedBy?: (number | null) | User;
        /**
         * Soft-delete del collaborator — si tiene valor, el acceso fue revocado
         */
        revokedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  createdBy?: (number | null) | User;
  /**
   * Si este dataset es un clon, referencia al dataset original (v2+)
   */
  originDatasetId?: (number | null) | Dataset;
  /**
   * Soft-delete. Si tiene valor, el dataset está eliminado. Solo sysadmin puede restaurar.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  /**
   * Dataset al que pertenece este resource.
   */
  dataset: number | Dataset;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  /**
   * Tipo del recurso. No puede modificarse después de creado.
   */
  resourceType: 'file' | 'link';
  status?: ('active' | 'archived' | 'disabled') | null;
  visibility?: ('private' | 'org_only' | 'public') | null;
  /**
   * Clave del archivo en el storage (S3 key, ruta, etc.).
   */
  fileStorageKey?: string | null;
  /**
   * Tamaño del archivo en bytes.
   */
  fileSize?: number | null;
  /**
   * MIME type del archivo (ej: text/csv, application/json).
   */
  mimeType?: string | null;
  /**
   * Hash del archivo (SHA-256) para verificación de integridad.
   */
  fileHash?: string | null;
  /**
   * URL del recurso externo.
   */
  externalUrl?: string | null;
  createdBy?: (number | null) | User;
  /**
   * Indica si este resource alguna vez fue parte de una versión publicada.
   */
  everPublished?: boolean | null;
  /**
   * Si está marcado, este resource no se incluirá en la próxima versión del dataset.
   */
  excludeFromNextVersion?: boolean | null;
  /**
   * Soft-delete. Si tiene valor, el resource está eliminado.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action:
    | 'DATASET_SUBMITTED_FOR_REVIEW'
    | 'DATASET_APPROVED'
    | 'DATASET_REJECTED'
    | 'DATASET_RETURNED_TO_DRAFT'
    | 'DATASET_VISIBILITY_ELEVATED'
    | 'DATASET_VISIBILITY_DEGRADED'
    | 'DATASET_VISIBILITY_REDUCED_BY_REVIEWER'
    | 'DATASET_ARCHIVED'
    | 'DATASET_UNARCHIVED'
    | 'DATASET_DISABLED'
    | 'DATASET_ENABLED'
    | 'DATASET_SOFT_DELETED'
    | 'DATASET_RESTORED'
    | 'DATASET_CLONED'
    | 'PURGE_REQUESTED'
    | 'PURGE_EXECUTED'
    | 'COLLABORATOR_ADDED'
    | 'COLLABORATOR_REMOVED'
    | 'COLLABORATOR_ROLE_CHANGED'
    | 'STEWARD_ASSIGNED'
    | 'STEWARD_REVOKED'
    | 'RESOURCE_VISIBILITY_CHANGED'
    | 'RESOURCE_VISIBILITY_REDUCED_BY_REVIEWER'
    | 'RESOURCE_ARCHIVED'
    | 'RESOURCE_DISABLED'
    | 'RESOURCE_SOFT_DELETED'
    | 'RESOURCE_RESTORED'
    | 'PURGE_RESOURCE'
    | 'ORG_OWNERSHIP_TRANSFERRED'
    | 'ORG_DISABLED'
    | 'USER_DEACTIVATED'
    | 'USER_ROLE_CHANGED'
    | 'MEMBERSHIP_CREATED'
    | 'MEMBERSHIP_REMOVED';
  /**
   * Usuario que realizó la acción. R8: siempre requerido.
   */
  actor: number | User;
  targetType: 'dataset' | 'resource' | 'organization' | 'user' | 'org_membership';
  /**
   * ID de la entidad afectada.
   */
  targetId: string;
  /**
   * Org a la que pertenece el evento — para filtrado por owner (R4).
   */
  organizationId?: (number | null) | Organization;
  /**
   * Datos del evento: diff, hashes SHA256 de campos extensos, campos anteriores/nuevos.
   */
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Justificación — requerida para las acciones marcadas en el catálogo (R6).
   */
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  organization: number | Organization;
  /**
   * Usuarios del team. Solo pueden ser de la misma org (R2).
   */
  members?: (number | User)[] | null;
  /**
   * Desactivar bloquea nuevas asignaciones. No revoca permisos expandidos. (R8)
   */
  isActive?: boolean | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'org-memberships';
        value: number | OrgMembership;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'datasets';
        value: number | Dataset;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  systemRole?: T;
  isActive?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  logo?: T;
  isActive?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "org-memberships_select".
 */
export interface OrgMembershipsSelect<T extends boolean = true> {
  user?: T;
  organization?: T;
  orgRole?: T;
  joinedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  parent?: T;
  level?: T;
  isActive?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  usageCount?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets_select".
 */
export interface DatasetsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  summary?: T;
  description?: T;
  organization?: T;
  category?: T;
  tags?: T;
  license?: T;
  licenseCustom?: T;
  status?: T;
  editorialStatus?: T;
  visibility?: T;
  visibilityRequest?: T;
  visibilityRequestedAt?: T;
  collaborators?:
    | T
    | {
        user?: T;
        role?: T;
        assignmentType?: T;
        teamId?: T;
        orgIdAtAssignment?: T;
        assignedBy?: T;
        revokedAt?: T;
        id?: T;
      };
  createdBy?: T;
  originDatasetId?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  dataset?: T;
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  resourceType?: T;
  status?: T;
  visibility?: T;
  fileStorageKey?: T;
  fileSize?: T;
  mimeType?: T;
  fileHash?: T;
  externalUrl?: T;
  createdBy?: T;
  everPublished?: T;
  excludeFromNextVersion?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  actor?: T;
  targetType?: T;
  targetId?: T;
  organizationId?: T;
  payload?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  organization?: T;
  members?: T;
  isActive?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}